### ISSUE TITLE
Fixing it properly in PHP? (Artax)

### ISSUE THREAD

**Issue by bwoebi** [httpoxy/httpoxy-org#8]
I'm a contributor to the amphp project, thus also to amphp/artax, which you mentioned.

As far as I see, the only way to fix it is a) renaming/removing it entirely or b) checking against used SAPIs (i.e. disallow any web SAPIs).

Additionally I had the idea of not using HTTP_PROXY in case it matches with the header, but then the attacker can still disable the proxy by intentionally passing the same proxy in the header as the environment variable contains...

Or do you have any better suggestions?

My issue with a) renaming is http_proxy being quite a common environment variable also used elsewhere. Users would have to declare it twice basically, once for artax, once for everything else.
b) checking against SAPIs is an option, but white-/blacklists would need to be updated and is not safe (blacklist) or not providing support (whitelist) for new/custom SAPIs.

**Comment by dominics** [comment]
I strongly recommend you follow the mitigation that libwww-perl and Ruby applied. That is: if CGI appears to be in use, HTTP_PROXY cannot be trusted. Now, because everything but the CLI SAPI is essentially "emulated CGI", I suggest you only ever trust HTTP_PROXY or http_proxy when `PHP_SAPI == 'cli'`. (The issue with the 'lower-case mitigation' is getenv appears to be case-insensitive under mod_php, etc.)

For *all* other cases, you should only trust CGI_HTTP_PROXY.

That advice might change once you see what the PHP team are going to do to the `getenv` method (looks like there will be a second parameter, `$local = false` that can be used to only get safe local values). But you might not be able to use that if you need to support older PHP versions.

**Comment by bwoebi** [comment]
`$local = false` is only useful in case it's not real CGI though? That sounds like a half-baked mitigation attempt.

Also phpdbg SAPI for example is also a CLI environment; so I probably should go with `PHP_SAPI == 'cli' || PHP_SAPI == 'phpdbg'`. Doing that then.

**Comment by dominics** [comment]
Yeah, that looks good.
